apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cwp-agents-dev-proj.yaml
  namespace: argocd-dev-projects
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
