apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cwp-sass-dev-proj
  namespace: argocd  #Must be in 'argocd' ns in order to be appeared in UI
  labels:
    domain: config
    tier: projects

spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  - namespace: '*'
    server: https://3EB3DC8AF129F3A4543FE2EF568D1494.yl4.eu-west-1.eks.amazonaws.com
  - namespace: '*'
    server: https://3969BC3980538D1D0367E610E43745D6.sk1.eu-west-1.eks.amazonaws.com
  - namespace: '*'
    server: https://55341330D7642D10A93C906543B43C7B.eks.eu-west-1.eks.amazonaws.com

  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
