apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: divvy-rds-dev-proj
  namespace: argocd #Must be in 'argocd' ns in order to be appeared in UI
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
