apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 01-argocd-dev
  namespace: argocd
  labels:
    domain: config
    level: tier-root
    tier: argocd
spec:
  project: default
  source:
    path: dev_cluster/01-argocd-infra-helm
    repoURL: https://github.com/rjackoby-r7/csp-devops-argocd-config.git
    targetRevision: HEAD

  destination:
    namespace: '*'
    server: https://kubernetes.default.svc