apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 07-deployments-dev
  namespace: argocd
  labels:
    domain: config
    level: tier-root
    tier: deployments
spec:
  project: default
  source:
    path: dev_cluster/07-org-units
    repoURL: https://github.com/rjackoby-r7/csp-devops-argocd-config.git
    targetRevision: HEAD
    directory:
      recurse: true

  destination:
    namespace: '*'
    server: https://kubernetes.default.svc