apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 06-projects-dev
  namespace: argocd
  labels:
    level: tier-root
    tier: projects
spec:
  project: default
  source:
    path: dev_cluster/06-projects
    repoURL: https://github.com/rjackoby-r7/csp-devops-argocd-config.git
    targetRevision: HEAD

  destination:
    namespace: '*'
    server: https://kubernetes.default.svc