apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 05-repos-dev
  namespace: argocd
  labels:
    level: tier-root
    tier: repos
spec:
  project: default
  source:
    path: dev_cluster/05-repos
    repoURL: https://github.com/rjackoby-r7/csp-devops-argocd-config.git
    targetRevision: HEAD

  destination:
    namespace: '*'
    server: https://kubernetes.default.svc