apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-crossplane-def-root-dev
  namespace: argocd
  labels:
    tier: infra
spec:
  project: default

  source:
    path: . #dev
    repoURL: https://github.com/rjackoby-r7/csp-devops-crossplane-def.git
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}

  destination:
    namespace: '*'
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      selfHeal: true
      prune: true