apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-infra-deployments-root-dev
  namespace: argocd
  labels:
    level: tier-root
    tier: infra

spec:
  project: default

  source:
    path: infra-deploy
    repoURL: https://github.com/rjackoby-r7/csp-devops-argocd-deploy.git
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}

  destination:
    namespace: infra-deployments-claims-ns
    server: https://kubernetes.default.svc

  #syncPolicy:
  #  automated:
  #    selfHeal: true
  #    prune: true