apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-projects-root-dev
  namespace: argocd
  labels:
    level: tier-root
    tier: config
spec:
  project: default
  source:
    path: projects/dev
    repoURL: https://github.com/rjackoby-r7/csp-devops-argocd-config.git
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}

  destination:
    namespace: '*'
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      selfHeal: true
      prune: true