apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-projects-root-dev
  namespace: argocd
spec:
  project: argocd-base-apps-and-projects

  source:
    path: projects/dev
    repoURL: https://github.com/rjackoby-r7/csp-devops-argocd-config.git
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}

  destination:
    namespace: '*'
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true