---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: dv-dev
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds-dv-dev
      key: creds

