namespace: argocd
project:   default
labels:
  level: component
  tier: plugins

applicationset:
  source:
    repoURL: http://alcide-argo-test.s3-website-us-east-1.amazonaws.com/new-structure/cluster-level-charts/
    chart: argocd-applicationset
    targetRevision: 1.0.0

  destination:
    namespace: argocd
    server:    https://kubernetes.default.svc

crossplane:
  source:
    repoURL: http://alcide-argo-test.s3-website-us-east-1.amazonaws.com/new-structure/cluster-level-charts/
    chart: crossplane
    targetRevision: 1.3.0

  destination:
    namespace: crossplane-system
    server:    https://kubernetes.default.svc

  provider_config_name: divvy-dev