namespace: argocd #argocd-controllers-and-plugins-apps-dev-ns TODO: Understand why changing this to other ns rather then argocd will cause it to lose track on resources and not showing them
project: controllers-or-plugins-dev-proj

crossplane:
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: 1.3.0
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc

applicationset:
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-applicationset
    targetRevision: 1.0.0
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc