apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-controllers-and-plugins
  namespace: argocd
spec:
  project: default

  source:
    path: additional_controllers_or_plugins
    repoURL: https://github.com/rjackoby-r7/csp-devops-argocd-config.git
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}

  destination:
    namespace: '*'
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      selfHeal: true
      prune: true