apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applicationset-installation
  namespace: argocd-controllers-and-plugins-apps-dev-ns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  source:
    repoURL:        {{ .Values.applicationset.source.repoURL }}
    chart:          {{ .Values.applicationset.source.chart }}
    targetRevision: {{ .Values.applicationset.source.targetRevision }}
  destination:
    namespace: {{ .Values.applicationset.destination.namespace }}
    server:    {{ .Values.applicationset.destination.server }}